### ISSUE TITLE
angle install 

### ISSUE THREAD

**Issue by 7dir** [aframevr/angle#20]
```
$ angle install aframe-alongpath-component index.html
Installing A-Frame component `aframe-alongpath-component` to `index.html`
Detected A-Frame version 0.5.0
C:\src\angle\lib\install.js:50
  if (moduleName in registry[version].components) {
                                     ^

TypeError: Cannot read property 'components' of undefined
    at Command.install (C:\src\angle\lib\install.js:50:38)
    at Command.listener (C:\src\angle\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (C:\src\angle\node_modules\commander\index.js:615:12)
    at Command.parse (C:\src\angle\node_modules\commander\index.js:458:21)
    at Object.<anonymous> (C:\src\angle\index.js:23:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by 7dir** [comment]
so aframe-component should exist in npm packages!

**Comment by perrychen901105** [comment]
@7dir Hello, I meet the same problem with your's, can you tell me how you fix this?

**Comment by 7dir** [comment]
@perrychen901105 
add some components

```
yarn add aframe-some-component
```
then import to index.js
```js
import aframe-some-component
```

or add to index.html

```html
<script src="aframe-some-component"></script>
```
